; 本地的MySQL数据库配置信息
[MYSQL]
Host = localhost
User = root
PassWord = hongshulin
Port = 3306
Charset = utf8
DataBase = vuln

[MSF]
Header = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
Username = hongshulin
PassWord = QUluaUAxMzE0Lg==
Host = 0.0.0.0
Port = 55553

[WEB]
Timeout = 5
ResType = ['Document', 'Font']

[SQLMAP]
Host = localhost
Port = 8775
Cmd = python src/core/sqlmap/sqlmapapi.py -s

[FOFA]
Email = 15723051314@163.com
Key = 4ac7e56c095cf0b70d68eaf8ad81178a

[VULN]
JsonApi = https://services.nvd.nist.gov/rest/json/cves/2.0

[CWE]
Api = /api/v1
